version: '3.8'

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000" # Porta padrão do DynamoDB local
    networks:
      - app-network
    command: -jar DynamoDBLocal.jar -sharedDb # Comando equivalente ao que você usou no Docker CLI
  elasticmq:
    image: softwaremill/elasticmq-native:1.6.12
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - app-network
    volumes:
      - ./docker/elasticmq.conf:/opt/elasticmq.conf
    command: -Dconfig.file=/opt/elasticmq.conf
  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   container_name: app
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: fastfood
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

networks:
  app-network: