name: Build and Deploy to EKS with Helm

on:
  push:
    branches: [ feat/deploy ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: fiap-fastfood
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME}}
  HELM_RELEASE_NAME: fastfood-order-service

jobs:
  build-and-deploy:
    name: Build and Deploy with Helm
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
    
    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.3'
    
    - name: Diagnose pre-deployment
      run: |
        echo "Nodes no cluster:"
        kubectl get nodes || echo "Falha ao listar nodes"
        echo "Recursos existentes:"
        kubectl get all -n default || echo "Falha ao listar recursos"

    - name: Configurar credenciais AWS no Kubernetes
      run: |
        # Criar secret para as credenciais AWS
        kubectl create secret generic aws-credentials \
          --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --from-literal=AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} \
          --namespace default \
          --dry-run=client -o yaml | kubectl apply -f -
          
        echo "Secret aws-credentials criado/atualizado com sucesso"

    - name: Configurar secrets para AWS SQS
      run: |
        kubectl create secret generic aws-sqs-config \
          --from-literal=AWS_ORDER_CREATED_QUEUE_URL=${{ secrets.AWS_ORDER_CREATED_QUEUE_URL }} \
          --from-literal=AWS_PAYMENT_COMPLETED_QUEUE_URL=${{ secrets.AWS_PAYMENT_COMPLETED_QUEUE_URL }} \
          --namespace default \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to EKS with Helm (sem wait)
      run: |
        helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm \
          --set image.repository=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }} \
          --set image.tag=${{ github.sha }} \
          --namespace default \
          --create-namespace

    - name: Verificar status do deploy
      if: always()
      run: |
        echo "Aguardando pods inicializarem (30s)..."
        sleep 30
        
        echo "Status dos pods:"
        kubectl get pods -n default || echo "Falha ao listar pods"
        
        echo "Detalhes dos pods:"
        POD_NAME=$(kubectl get pods -n default -l app=fastfood-order-service -o jsonpath="{.items[0].metadata.name}" 2>/dev/null || echo "")
        
        if [ -n "$POD_NAME" ]; then
          kubectl describe pod $POD_NAME -n default
          kubectl logs $POD_NAME -n default --all-containers || echo "Não foi possível obter logs"
        fi
        
        echo "Eventos recentes:"
        kubectl get events -n default --sort-by='.lastTimestamp' | tail -20

    - name: Obter URL da aplicação
      if: always()
      run: |
        echo "Verificando informações do serviço..."
        kubectl get svc ${{ env.HELM_RELEASE_NAME }} -n default
        
        # Aguarda o LoadBalancer obter um endereço externo
        echo "Aguardando o LoadBalancer provisionar um endereço externo (pode levar alguns minutos)..."
        kubectl wait --for=jsonpath='{.status.loadBalancer.ingress[0].hostname}' svc/${{ env.HELM_RELEASE_NAME }} -n default --timeout=300s || echo "Tempo limite excedido aguardando URL externa"
        
        # Obtém e exibe o endereço externo
        LB_ENDPOINT=$(kubectl get svc ${{ env.HELM_RELEASE_NAME }} -n default -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        
        if [ -n "$LB_ENDPOINT" ]; then
          echo "✅ A aplicação está disponível em: http://${LB_ENDPOINT}"
          echo "::set-output name=app_url::http://${LB_ENDPOINT}"
        else
          echo "⚠️ LoadBalancer ainda não tem um endereço externo atribuído."
        fi